import type { VersionSnapshot } from './diff';

export interface VersionMetadata {
  createdAt: string;
  creatorId: string;
  id: string;
  note?: string;
  sequence: number;
}

export interface VersionEntry extends VersionMetadata {
  snapshot: VersionSnapshot;
}

export type VersionHistoryEntry =
  | { kind: 'full'; version: VersionEntry }
  | { kind: 'metadataOnly'; version: VersionMetadata };

/** Most recent versions kept with full content client-side; older ones keep metadata only. */
export const MAX_FULL_VERSIONS = 50;

const toMetadata = (version: VersionEntry | VersionMetadata): VersionMetadata => ({
  createdAt: version.createdAt,
  creatorId: version.creatorId,
  id: version.id,
  ...(version.note !== undefined ? { note: version.note } : {}),
  sequence: version.sequence,
});

/**
 * Prepends `version` to `history` (newest first) and keeps only the most
 * recent `MAX_FULL_VERSIONS` entries with their full snapshot; older entries
 * are demoted to metadata-only rather than dropped, so history length never
 * shrinks and nothing is ever deleted.
 */
export function appendVersionToHistory(
  history: readonly VersionHistoryEntry[],
  version: VersionEntry,
): VersionHistoryEntry[] {
  const withNewVersion: VersionHistoryEntry[] = [{ kind: 'full', version }, ...history];

  return withNewVersion.map((entry, index) =>
    index < MAX_FULL_VERSIONS || entry.kind === 'metadataOnly'
      ? entry
      : { kind: 'metadataOnly', version: toMetadata(entry.version) },
  );
}

export interface RestoreVersionInput {
  floorId: string;
  /** Metadata for the new version being created; generated by the caller so this stays a pure function. */
  newVersion: VersionMetadata;
  /** The old version being restored — must carry its full snapshot. */
  sourceVersion: VersionEntry;
}

export interface RestoreVersionResult {
  floorId: string;
  restoredVersion: VersionEntry;
}

/**
 * Restores an old version by producing a brand-new version whose content
 * equals `sourceVersion`'s snapshot. Restoring always moves forward — it
 * never mutates, deletes, or reorders existing versions; the caller appends
 * `restoredVersion` onto history via `appendVersionToHistory` like any other
 * new version.
 */
export function restoreVersion(input: RestoreVersionInput): RestoreVersionResult {
  const { floorId, newVersion, sourceVersion } = input;

  return {
    floorId,
    restoredVersion: {
      ...newVersion,
      snapshot: sourceVersion.snapshot,
    },
  };
}
