// Mock-pairing table of coverage/phase01-be.md, generated from the spec sources (BUG-103/104). Usage (from qa/):
//   node tools/mock-pairs.mjs            check: exit 1 if a [mocked response] test has no row, or a row no test
//   node tools/mock-pairs.mjs --write    also rewrite the table between the markers with today's file:line
// Rows are keyed by a fragment of the test title, never by line number, so the lines are re-read on every run.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const SUITE = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const COVERAGE = join(SUITE, 'coverage', 'phase01-be.md');
const START = '<!-- mock-pairs:start (generated by tools/mock-pairs.mjs, do not edit by hand) -->';
const END = '<!-- mock-pairs:end -->';
const SPECS = {
  auth_edge: 'tests/phase01_auth_edge.spec.ts',
  auth_ui: 'tests/phase01_auth_ui.spec.ts',
  recovery_edge: 'tests/phase01_recovery_edge.spec.ts',
};

/** spec key · unique title fragment · short label · endpoint + faked response · pairing. */
const PAIRS = [
  ['auth_edge', 'server unreachable at bootstrap', 'SCR-01 server unreachable at bootstrap', 'refresh → network loss', 'unpairable: network loss'],
  ['auth_edge', 'session layer never loads', 'session layer never loads', 'app JS chunks aborted (no API)', 'unpairable: not an API'],
  ['auth_edge', 'a refresh fails mid-session', 'refresh fails mid-session', 'refresh → network loss', 'unpairable: network loss'],
  ['auth_edge', '[mocked response] 500 → "Có trục trặc" strip, no reset action', 'login 500', 'login → 500', 'unpairable: 5xx'],
  ['auth_edge', '[mocked response] network failure → "Mất kết nối máy chủ…" strip with no separate title', 'login network failure', 'login → network loss', 'unpairable: network loss'],
  ['auth_edge', 'submit locked 60 s whatever Retry-After says', 'login 429', 'login → 429 RATE_LIMITED', 'paired: "5 attempts on one unknown address → … 6th → 429 RATE_LIMITED + Retry-After 10"'],
  ['auth_edge', '[mocked response] 403 ACCOUNT_DISABLED', 'login 403 ACCOUNT_DISABLED', 'login → 403', 'paired: invitation test ("… right password 403 ACCOUNT_DISABLED …")'],
  ['auth_edge', '[mocked response] 403 ORIGIN_MISMATCH → "Máy chủ từ chối yêu cầu" strip, form stays', 'login 403 ORIGIN_MISMATCH', 'login → 403', 'paired: "foreign or missing Origin → 403 ORIGIN_MISMATCH on all six routes"'],
  ['auth_edge', '[mocked response] 422 VALIDATION field "password"', 'login 422 field password / unknown field', 'login → 422 VALIDATION', 'paired: "login 422 … a password of 4 code points that the FE sends" (same `BE_SHORT_PASSWORD` as the UI box, BUG-094), "login 422 … extra body key"'],
  ['auth_edge', 'follow-up refresh cannot reach the server', 'login 204, follow-up refresh unreachable', 'refresh → network loss', 'unpairable: network loss (login 204 itself paired by the rotation test)'],
  ['auth_edge', 'the session does not open (real refresh 401)', 'login 204 with no cookie, real refresh 401', 'login → 204 without Set-Cookie', 'unpairable: the real BE always sets cookies on 204 (router.py:183-191; the state = a browser that drops cookies). The refresh 401 is real and paired by "refresh without a cookie … 401 UNAUTHENTICATED"'],
  ['auth_edge', '[mocked response] sending: "Đang gửi…"', 'forgot "sending" then sent', 'password-reset → held 204', 'paired: reset test ("request 204 + mailed link")'],
  ['auth_edge', '[mocked response] 429 → "Đã thử quá nhiều lần" / "Hãy đợi vài phút rồi thử lại." strip, send locked', 'forgot 429', 'password-reset → 429', 'unpairable: `recovery_ip` is IP-wide for 900 s'],
  ['auth_edge', '[mocked response] network / 403 ORIGIN_MISMATCH / 500', 'forgot network / 403 / 500 / 422 email', 'password-reset → each', '403 paired: origin test; 422 paired: "password-reset with an address zod .email() rejects"; network, 500 unpairable'],
  ['auth_edge', 'reset #token=bogus + valid matching passwords → [mocked response]', 'reset bogus token → 422 PASSWORD_RESET_TOKEN_INVALID', 'confirm → 422', 'paired: reset test (reuse → 422) + purpose test (invitation token → 422); same branch, router.py:286-287'],
  ['auth_edge', 'SCR-03 / SCR-04 · [mocked response] 500', 'SCR-03/04 500 / network / 429', 'accept, confirm → each', 'unpairable: 5xx, network loss, IP-wide 429'],
  ['auth_edge', 'SCR-03 · [mocked response] server unreachable at load', 'SCR-03 server unreachable at load', 'refresh → network loss', 'unpairable: network loss'],
  ['auth_edge', 'the retry ladder stops after 8 attempts', 'SCR-01 retry ladder while the server is unreachable', 'refresh → network loss ×8, then real 401', 'unpairable: network loss (the closing 401 is real, paired by "refresh without a cookie … 401 UNAUTHENTICATED")'],
  ['auth_edge', '429 with Retry-After 120', 'forgot 429 with Retry-After 120', 'password-reset → 429 + Retry-After 120', 'unpairable: `recovery_ip` is an IP-wide limit (900 s window); the real Retry-After is the window left, not a chosen 120'],
  ['auth_edge', 'reset 204 but the logout cannot reach the server', 'reset 204, logout unreachable', 'confirm → 204; logout → network loss', 'unpairable: network loss (confirm 204 itself paired by the reset test)'],
  ['auth_ui', 'U01_login_strips_1024', 'U01_login_strips_1024', 'login → 401 INVALID_CREDENTIALS, 403 ORIGIN_MISMATCH', 'paired: lock test (401) + origin test (403)'],
  ['recovery_edge', '[mocked response] slow 500', 'SCR-03 / SCR-04 slow 500', 'accept / confirm → 500', 'unpairable: 5xx'],
  ['recovery_edge', '[mocked response] network failure → "Mất kết nối" strip, can resubmit', 'SCR-03 / SCR-04 network failure', 'accept / confirm → network loss', 'unpairable: network loss'],
  ['recovery_edge', '[mocked response] 429 RATE_LIMITED', 'SCR-03 / SCR-04 429', 'accept / confirm → 429', 'unpairable: `recovery_ip` is IP-wide for 900 s'],
  ['recovery_edge', '[mocked response] 403 ORIGIN_MISMATCH', 'SCR-03 / SCR-04 403 ORIGIN_MISMATCH', 'accept / confirm → 403', 'paired: origin test'],
  ['recovery_edge', '[mocked response] 422 VALIDATION field "token"', 'SCR-03 / SCR-04 422 field token', 'accept / confirm → 422 VALIDATION token', 'paired: "accept with a 513-character token", "confirm with a 513-character token"'],
  ['recovery_edge', '[mocked response] 422 VALIDATION field fullName / password', 'SCR-03 422 field fullName / password', 'accept → 422', 'paired: "accept with a whitespace-only fullName" (+ 121, Cc), "accept with a password of 4 code points" (same `BE_SHORT_PASSWORD`, BUG-094)'],
  ['recovery_edge', '[mocked response] 204 but no session', 'SCR-03 204 but no session', 'accept → 204 without Set-Cookie', '204 + body (hash token, trimmed name) paired: invitation test. The "no session" part is unpairable: the real BE always opens a session (router.py:356-364)'],
  ['recovery_edge', 'SCR-03 · [mocked response] server unreachable at load', 'SCR-03 server unreachable at load', 'refresh → network loss', 'unpairable: network loss'],
  ['recovery_edge', '[mocked response] signed in, 204', 'SCR-03 signed in, 204 → session opens', 'accept → 204', 'paired: invitation test + purpose test (accept carrying a live session → 204, that session revoked "replaced")'],
  ['recovery_edge', '[mocked response] 422 VALIDATION field newPassword', 'SCR-04 422 field newPassword', 'confirm → 422', 'paired: "confirm with a newPassword of 4 code points" (same `BE_SHORT_PASSWORD`, BUG-094)'],
  ['recovery_edge', '[mocked response] 204 → success line → signOut', 'SCR-04 204 → logout', 'confirm → 204', 'paired: reset test (confirm 204 clears cookies) + logout test'],
];

const TEST_LINE = /^\s*test\(\s*['`](.*)$/u;
const mocked = [];
for (const [key, path] of Object.entries(SPECS)) {
  readFileSync(join(SUITE, path), 'utf8')
    .split(/\r?\n/u)
    .forEach((line, index) => {
      const title = TEST_LINE.exec(line)?.[1];
      if (title?.includes('[mocked response]')) mocked.push({ key, line: index + 1, title });
    });
}

const rows = [];
const gaps = [];
const used = new Set();
for (const test of mocked) {
  const hits = PAIRS.filter(([key, fragment]) => key === test.key && test.title.includes(fragment));
  if (hits.length !== 1) {
    gaps.push(`${test.key}:${test.line} ${hits.length === 0 ? 'no row' : `${hits.length} rows`}: ${test.title.slice(0, 90)}`);
    continue;
  }
  used.add(hits[0]);
  const [key, , label, endpoint, pairing] = hits[0];
  rows.push(`| ${key}:${test.line} ${label} | ${endpoint} | ${pairing} |`);
}
for (const pair of PAIRS) if (!used.has(pair)) gaps.push(`row matches no test: ${pair[0]} "${pair[1]}"`);

const table = [
  START,
  `${mocked.length} \`[mocked response]\` tests in source (a test inside a per-screen loop runs once per screen).`,
  '',
  '| UI test (file:line) | Endpoint + faked response | Pairing |',
  '|---|---|---|',
  ...rows,
  END,
].join('\n');

if (process.argv.includes('--write')) {
  const doc = readFileSync(COVERAGE, 'utf8');
  const [from, to] = [doc.indexOf(START), doc.indexOf(END)];
  if (from < 0 || to < 0) throw new Error(`markers missing in ${COVERAGE}`);
  writeFileSync(COVERAGE, doc.slice(0, from) + table + doc.slice(to + END.length));
}
console.log(`mocked tests ${mocked.length}, rows ${rows.length}, pairGaps ${gaps.length}`);
for (const gap of gaps) console.log(`GAP ${gap}`);
process.exit(gaps.length === 0 ? 0 : 1);
