/**
 * Bảng 47 màn × bảy trạng thái mà `StateGallery` duyệt qua.
 *
 * Dữ liệu ở đây lấy từ khảo sát I2 (đọc trực tiếp 46 file `*.stories.tsx`
 * trong `src/screens/**`) cộng chính trang `StateGallery`. Khi hai nguồn lệch
 * nhau, khảo sát I2 thắng vì nó đọc file thật — hợp đồng
 * (`stateGalleryTypes.ts`) chỉ định hình dạng, không định nội dung.
 *
 * `presentCount`/`totalCount`/`screenCount` KHÔNG viết tay ở đây — chúng do
 * {@link screenCoverage} và {@link galleryCoverage} tính từ `states` bên dưới,
 * để một dòng dữ liệu sửa sai không kéo theo một con số quên cập nhật.
 */

import { SEVEN_STATE_LABELS, SEVEN_STATES, type SevenState } from '@/lib/testing/sevenStateScenarios';

import type {
  GalleryCoverage,
  GalleryManifest,
  GalleryScreenEntry,
  ScreenCoverage,
  ScreenGroup,
  ScreenGroupId,
} from './stateGalleryTypes';

/* ── Tám nhóm của cây bên trái (A-H) ──────────────────────────────────────── */

export const SCREEN_GROUPS: readonly ScreenGroup[] = [
  { id: 'A', label: 'xác thực và tài khoản' },
  { id: 'B', label: 'quản trị và thanh toán' },
  { id: 'C', label: 'bảng điều khiển và dự án' },
  { id: 'D', label: 'tải lên và giới thiệu' },
  { id: 'E', label: 'xử lý bản vẽ CAD' },
  { id: 'F', label: 'soát chất lượng' },
  { id: 'G', label: 'quy tắc và xuất' },
  { id: 'H', label: 'xem mô hình và hệ thống' },
] as const;

/* ── Một định nghĩa màn thô, trước khi dựng thành `GalleryScreenEntry` ───── */

interface ScreenDef {
  readonly id: string;
  readonly name: string;
  readonly area: string;
  readonly group: ScreenGroupId;
  readonly label: string;
  /** Tên export story thật cho từng trạng thái, `null` khi màn đó thiếu. */
  readonly storyExportNames: Readonly<Record<SevenState, string | null>>;
}

function buildEntry(def: ScreenDef): GalleryScreenEntry {
  return {
    id: def.id,
    name: def.name,
    area: def.area,
    group: def.group,
    label: def.label,
    states: SEVEN_STATES.map((state) => ({
      state,
      label: SEVEN_STATE_LABELS[state],
      storyExportName: def.storyExportNames[state],
    })),
  };
}

/* ── 46 màn từ khảo sát I2, cộng chính trang này (#47) ────────────────────── */

const SCREEN_DEFS: readonly ScreenDef[] = [
  {
    id: 'account/AccountSettings',
    name: 'AccountSettings',
    area: 'account',
    group: 'A',
    label: 'cài đặt tài khoản',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'admin/ModelLibrary',
    name: 'ModelLibrary',
    area: 'admin',
    group: 'B',
    label: 'thư viện model',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'admin/UserManagement',
    name: 'UserManagement',
    area: 'admin',
    group: 'B',
    label: 'quản lý người dùng',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'auth/AuthScreen',
    name: 'AuthScreen',
    area: 'auth',
    group: 'A',
    label: 'đăng nhập',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Sending',
      partial: 'Partial',
      error: 'WrongPassword',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'billing/BillingScreen',
    name: 'BillingScreen',
    area: 'billing',
    group: 'B',
    label: 'thanh toán và gói dịch vụ',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Ready',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'dashboard/ProjectDashboard',
    name: 'ProjectDashboard',
    area: 'dashboard',
    group: 'C',
    label: 'bảng điều khiển dự án',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'export/ExportPanel',
    name: 'ExportPanel',
    area: 'export',
    group: 'G',
    label: 'xuất mô hình',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'export/ShareDialog',
    name: 'ShareDialog',
    area: 'export',
    group: 'G',
    label: 'chia sẻ liên kết',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'export/VersionHistory',
    name: 'VersionHistory',
    area: 'export',
    group: 'G',
    label: 'lịch sử phiên bản',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'onboarding/WelcomeScreen',
    name: 'WelcomeScreen',
    area: 'onboarding',
    group: 'D',
    label: 'chào mừng',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'pipeline/CadBranchConfirm',
    name: 'CadBranchConfirm',
    area: 'pipeline',
    group: 'E',
    label: 'phát hiện tệp CAD',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'pipeline/PipelineFailure',
    name: 'PipelineFailure',
    area: 'pipeline',
    group: 'E',
    label: 'xử lý thất bại',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'pipeline/PipelineGraph',
    name: 'PipelineGraph',
    area: 'pipeline',
    group: 'E',
    label: 'biểu đồ tiến trình xử lý',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'pipeline/ProcessingScreen',
    name: 'ProcessingScreen',
    area: 'pipeline',
    group: 'E',
    label: 'đang xử lý bản vẽ',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'pipeline/ScaleCalibration',
    name: 'ScaleCalibration',
    area: 'pipeline',
    group: 'E',
    label: 'hiệu chỉnh tỷ lệ',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'project/CreateProjectModal',
    name: 'CreateProjectModal',
    area: 'project',
    group: 'C',
    label: 'tạo dự án mới',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'project/ProjectSettings',
    name: 'ProjectSettings',
    area: 'project',
    group: 'C',
    label: 'cài đặt dự án',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'project/ShareScreen',
    name: 'ShareScreen',
    area: 'project',
    group: 'C',
    label: 'chia sẻ dự án',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'qc/AxisGridManager',
    name: 'AxisGridManager',
    area: 'qc',
    group: 'F',
    label: 'quản lý trục và lưới',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'qc/DimensionOcrReview',
    name: 'DimensionOcrReview',
    area: 'qc',
    group: 'F',
    label: 'soát kích thước OCR',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'qc/FloorManager',
    name: 'FloorManager',
    area: 'qc',
    group: 'F',
    label: 'quản lý tầng',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'qc/ObjectLayerReview',
    name: 'ObjectLayerReview',
    area: 'qc',
    group: 'F',
    label: 'soát lớp đối tượng',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'qc/RoomLabelReview',
    name: 'RoomLabelReview',
    area: 'qc',
    group: 'F',
    label: 'soát nhãn phòng',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'qc/ThicknessStandardization',
    name: 'ThicknessStandardization',
    area: 'qc',
    group: 'F',
    label: 'chuẩn hoá độ dày tường',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'qc/WallLayerReview',
    name: 'WallLayerReview',
    area: 'qc',
    group: 'F',
    label: 'soát lớp tường',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'rules/RuleReport',
    name: 'RuleReport',
    area: 'rules',
    group: 'G',
    label: 'báo cáo quy tắc',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'rules/RuleSettings',
    name: 'RuleSettings',
    area: 'rules',
    group: 'G',
    label: 'cài đặt quy tắc',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Ready',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'rules/ViolationDetail',
    name: 'ViolationDetail',
    area: 'rules',
    group: 'G',
    label: 'chi tiết vi phạm',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'system/AccessDenied',
    name: 'AccessDenied',
    area: 'system',
    group: 'H',
    label: 'từ chối truy cập',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'system/CollaborationLayer',
    name: 'CollaborationLayer',
    area: 'system',
    group: 'H',
    label: 'lớp cộng tác',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'system/EditorTour',
    name: 'EditorTour',
    area: 'system',
    group: 'H',
    label: 'hướng dẫn dùng trình soạn thảo',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'system/MobileViewer',
    name: 'MobileViewer',
    area: 'system',
    group: 'H',
    label: 'xem trên điện thoại',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'system/NotFound',
    name: 'NotFound',
    area: 'system',
    group: 'H',
    label: 'không tìm thấy trang',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'system/NotificationCenter',
    name: 'NotificationCenter',
    area: 'system',
    group: 'H',
    label: 'trung tâm thông báo',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'ErrorState',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'upload/FloorUploadScreen',
    name: 'FloorUploadScreen',
    area: 'upload',
    group: 'D',
    label: 'tải bản vẽ lên',
    storyExportNames: {
      empty: 'Empty',
      loading: 'Loading',
      partial: 'Partial',
      error: 'Error',
      success: 'Success',
      forbidden: 'Forbidden',
      collapsed: 'Collapsed',
    },
  },
  {
    id: 'upload/InputQualityGate',
    name: 'InputQualityGate',
    area: 'upload',
    group: 'D',
    label: 'kiểm tra chất lượng đầu vào',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/ExplodedView',
    name: 'ExplodedView',
    area: 'viewer',
    group: 'H',
    label: 'tách tầng',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/FurnitureLibraryPanel',
    name: 'FurnitureLibraryPanel',
    area: 'viewer',
    group: 'H',
    label: 'thư viện nội thất',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/HistoryPanel',
    name: 'HistoryPanel',
    area: 'viewer',
    group: 'H',
    label: 'lịch sử thao tác',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/MeasurementTool',
    name: 'MeasurementTool',
    area: 'viewer',
    group: 'H',
    label: 'đo lường',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangDo',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/OverlayComparison',
    name: 'OverlayComparison',
    area: 'viewer',
    group: 'H',
    label: 'đối chiếu bản vẽ',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'ThanhCong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/PropertyInspector',
    name: 'PropertyInspector',
    area: 'viewer',
    group: 'H',
    label: 'xem thuộc tính đối tượng',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/RoomAreaPanel',
    name: 'RoomAreaPanel',
    area: 'viewer',
    group: 'H',
    label: 'diện tích phòng',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/Viewer3D',
    name: 'Viewer3D',
    area: 'viewer',
    group: 'H',
    label: 'xem mô hình 3D',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/ViewerShell',
    name: 'ViewerShell',
    area: 'viewer',
    group: 'H',
    label: 'khung xem mô hình',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  {
    id: 'viewer/WallGeometryEditor',
    name: 'WallGeometryEditor',
    area: 'viewer',
    group: 'H',
    label: 'chỉnh hình học tường',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
  /** Màn thứ 47: chính trang này. */
  {
    id: 'system/StateGallery',
    name: 'StateGallery',
    area: 'system',
    group: 'H',
    label: 'duyệt bảy trạng thái',
    storyExportNames: {
      empty: 'Rong',
      loading: 'DangTai',
      partial: 'MotPhan',
      error: 'Loi',
      success: 'Xong',
      forbidden: 'KhongCoQuyen',
      collapsed: 'ThuGon',
    },
  },
];

/* ── Manifest tổng ─────────────────────────────────────────────────────────── */

export const STATE_GALLERY_MANIFEST: GalleryManifest = {
  screens: SCREEN_DEFS.map(buildEntry),
  groups: SCREEN_GROUPS,
};

/* ── Dẫn xuất ─────────────────────────────────────────────────────────────── */

/** Số đếm của một màn: bao nhiêu trên bảy trạng thái có story thật. */
export function screenCoverage(entry: GalleryScreenEntry): ScreenCoverage {
  const missingLabels = entry.states
    .filter((s) => s.storyExportName === null)
    .map((s) => s.label);

  return {
    screenId: entry.id,
    presentCount: entry.states.length - missingLabels.length,
    totalCount: entry.states.length,
    missingLabels,
  };
}

/** Số đếm của cả trang, gộp từ {@link screenCoverage} của từng màn. */
export function galleryCoverage(manifest: GalleryManifest): GalleryCoverage {
  const perScreen = manifest.screens.map(screenCoverage);
  const incompleteScreens = perScreen.filter((c) => c.presentCount < c.totalCount);

  return {
    presentCount: perScreen.reduce((sum, c) => sum + c.presentCount, 0),
    totalCount: perScreen.reduce((sum, c) => sum + c.totalCount, 0),
    screenCount: manifest.screens.length,
    incompleteScreens,
  };
}
