/**
 * Cổng dữ liệu của S-33 — lịch sử phiên bản. Một file thuần: không React, không JSX,
 * nên nó chạy và test được ngoài một cây React, đúng khuôn
 * `ShareDialog/shareDialogGateway.ts` và `viewer/HistoryPanel/historyPanelGateway.ts`.
 *
 * Màn hình không tự so dữ liệu, không tự ghép câu và không bao giờ ghi đè. Bốn việc ở
 * đây đều là **nối lại** những hàm đã có: `diffVersions` so, `restoreVersion` +
 * `appendVersionToHistory` phục hồi, `resolveConflict` phân loại 409, `createUndoTicket`
 * mở cửa sổ hoàn tác.
 *
 * ## Bản kê nợ — thứ KHÔNG TÌM THẤY, và vì sao không bịa
 *
 * Bốn khoảng trống này đã được ghi trong docblock đầu `types.ts`; chép lại đây ở dạng
 * hệ quả kỹ thuật, vì file này là nơi từng khoảng trống biến thành một quyết định.
 *
 * 1. **Endpoint LIỆT KÊ phiên bản — NOT FOUND.** `src/api/endpoints.ts` chỉ có
 *    `spatial.version(projectId, versionId)`, một đường CHI TIẾT cần biết trước
 *    `versionId`. Không có `spatial.versions(projectId)`, và không có mock versioning nào
 *    trong `src/lib/testing`. Nên {@link VersionHistoryGateway.listVersions} **không ghép
 *    một đường mạng mới** — nó trả về lịch sử được **bơm vào** qua
 *    {@link CreateVersionHistoryGatewayOptions.entries}, hoặc gọi bộ nạp
 *    {@link CreateVersionHistoryGatewayOptions.loadVersions} mà nơi ráp truyền xuống.
 *    Ngày endpoint ấy tồn tại, bộ nạp đó là chỗ duy nhất phải sửa, và nó vẫn phải đi qua
 *    `src/lib/http` như `local/no-fetch-outside-http` đòi.
 *
 * 2. **Đường GHI phục hồi — NOT FOUND.** Không có `PUT`/`POST` nào cho phục hồi phiên
 *    bản, nên cũng không có nguồn 409 thật. `restoreVersion` là hàm THUẦN và
 *    `appendVersionToHistory` cũng vậy: cả hai chỉ dựng lịch sử mới trong bộ nhớ. Vì thế
 *    lượt ghi máy chủ là một tham số bơm vào —
 *    {@link CreateVersionHistoryGatewayOptions.commitRestore}. Không bơm thì phục hồi
 *    chạy hoàn toàn tại chỗ và **không nhánh nào ghi đè**; bơm rồi mà máy chủ trả 409 thì
 *    thân 409 đi thẳng vào `resolveConflict`. Không có nhánh "cứ ghi đè" ở bất kỳ đâu
 *    trong file này — cố ý, và {@link RestoreOutcome} cũng không có trường cho nó.
 *
 * 3. **Factory siêu dữ liệu phiên bản mới — NOT FOUND.** `RestoreVersionInput.newVersion`
 *    có chú thích ngay tại `restore.ts:51`: *"generated by the caller so this stays a pure
 *    function"*. Không có `nextSequence`/`generateVersionId` nào trong `src/lib` hay
 *    `src/store`. Nên {@link buildRestoredVersionMetadata} sinh nó **ở đây, bằng cách rõ
 *    ràng**: `id` từ `createUuid` của `src/lib/http` (bộ sinh id duy nhất của repo),
 *    `sequence` là số lớn nhất đang có cộng một, `createdAt` từ đồng hồ bơm vào,
 *    `creatorId` từ danh tính bơm vào. Đây là chỗ tầng logic còn thiếu, không phải một
 *    quy ước mới của màn hình.
 *
 * 4. **Tên người trong thân 409 — NOT FOUND.** `ConflictResponseBody` chỉ có
 *    `currentVersion` và `remoteChanges`; trường gần nhất là `RemoteFieldChange.changedBy`
 *    (`mergeStrategies.ts:12`, kiểu `string`) — **có thể là id, không chắc là tên**. Nên
 *    {@link toConflictNotice} tra `changedBy` sang tên hiển thị khi nơi ráp truyền
 *    {@link CreateVersionHistoryGatewayOptions.members}, và **lùi về chính chuỗi thô** khi
 *    không có danh sách. Một cái tên bịa ra còn tệ hơn một id thành thật.
 *
 * Thêm hai khả năng nữa không có đường, nên chúng là `false` và affordance tương ứng rời
 * khỏi DOM (R-69):
 *
 * - **Gắn nhãn phiên bản** — không endpoint nào gắn nhãn. `tagVersion` của hợp đồng là
 *   phương thức **tuỳ chọn**, {@link createVersionHistoryGateway} không cài nó khi không
 *   ai bơm vào, và `canTagVersion` bằng đúng "có ai bơm phương thức ấy vào không".
 * - **Xuất một phiên bản** — đây là **điều hướng** sang S-34, không phải một thao tác dữ
 *   liệu: màn không tự xuất gì, nó gọi `onExportVersion` do nơi gọi cấp xuống (R-73). Vì
 *   thế `VersionHistoryModel.canExportVersion` đúng bằng "nơi gọi có cấp callback đó
 *   không", và phép tính ấy nằm ở hook chứ không ở đây. Cờ dưới đây chỉ là đường bật thêm
 *   cho nơi ráp nào có sẵn đường xuất riêng; mặc định `false`.
 *
 * Hai khả năng CÓ THẬT: `canShowCurrentModel3d` và `canHighlightEntity`. Cả hai đứng trên
 * `mountViewerScene` (`screens/viewer/Viewer3D/viewer3dScene.ts:211`) —
 * `ViewerSceneFrame.selectedEntityIds` và `hoveredEntityId` có thật
 * (`viewerShellTypes.ts:225-250`), và `viewer3dScene.ts:618-634` đổi vật liệu theo id. Đó
 * là **tô màu nguyên khối**, không phải viền mảnh, và nó dựng mô hình **HIỆN TẠI** chứ
 * không dựng lại bản cũ.
 */

import { formatCalendarDate } from '@/lib/format/datetime';
import { createUuid } from '@/lib/http';
import { createUndoTicket, type UndoTicket } from '@/lib/mutations/undoTicket';
import { queryKeys } from '@/lib/query/queryKeys';
import {
  resolveConflict,
  type ConflictResponseBody,
  type FieldChange,
  type RemoteFieldChange,
} from '@/lib/versioning/conflict';
import { diffVersions, type DiffEntry, type VersionDiff } from '@/lib/versioning/diff';
import {
  appendVersionToHistory,
  restoreVersion,
  MAX_FULL_VERSIONS,
  type VersionEntry,
  type VersionHistoryEntry,
  type VersionMetadata,
} from '@/lib/versioning/restore';

import type {
  ConflictNoticeModel,
  RestoreOutcome,
  VersionHistoryCapabilities,
  VersionHistoryGateway,
} from './types';

/* -------------------------------------------------------------------------- */
/* 1 — Khoá bộ nhớ đệm (R-64)                                                 */
/* -------------------------------------------------------------------------- */

/**
 * Khoá của lượt đọc danh sách phiên bản.
 *
 * `queryKeys.version.byFloor(floorId)` đã có sẵn (`queryKeys.ts:136-141`) và
 * `invalidation.ts:120-127` đã liệt kê nó trong bảng vô hiệu hoá của `restoreVersion` —
 * nên đây không phải một nhánh khoá mới, chỉ là lượt đầu tiên có người tiêu thụ nó.
 */
export const versionsQueryKey = (floorId: string) => queryKeys.version.byFloor(floorId);

/* -------------------------------------------------------------------------- */
/* 2 — Câu nói ra khi một đường không có                                      */
/* -------------------------------------------------------------------------- */

/**
 * Câu hiện khi so sánh chạm vào một phiên bản chỉ còn siêu dữ liệu.
 *
 * Nói ra CHÍNH SÁCH thật (`MAX_FULL_VERSIONS` = 50 bản gần nhất giữ đủ nội dung,
 * `restore.ts:19-20`) chứ không nói "không tải được" — người đọc phải phân biệt được một
 * lượt tải hỏng với một phiên bản đã tới hạn lưu giữ.
 */
export const RETENTION_NOTICE = `chỉ ${MAX_FULL_VERSIONS} phiên bản gần nhất còn giữ đủ nội dung; bản này chỉ còn siêu dữ liệu nên không so sánh và không phục hồi được`;

/** Câu ném ra khi phục hồi hoặc so sánh gọi vào một phiên bản không còn ảnh chụp. */
export const SNAPSHOT_MISSING_REASON =
  'phiên bản này không còn ảnh chụp nội dung, nên không so sánh và không phục hồi được';

/** Câu nói ra khi chưa nơi nào bơm danh sách phiên bản vào màn. */
export const NO_VERSION_SOURCE_REASON =
  'chưa có nguồn dữ liệu phiên bản nào được nối vào màn này';

/* -------------------------------------------------------------------------- */
/* 3 — Tham số dựng cổng                                                      */
/* -------------------------------------------------------------------------- */

/** Một người có thể xuất hiện trong `changedBy` của thân 409. */
export interface VersionActor {
  readonly id: string;
  readonly name: string;
}

/** Thân 409 khi lượt ghi phục hồi bị máy chủ từ chối vì đã cũ. */
export interface CommitRestoreConflict {
  readonly kind: 'conflict';
  readonly body: ConflictResponseBody;
}

/** Lượt ghi phục hồi đã được máy chủ nhận. */
export interface CommitRestoreAccepted {
  readonly kind: 'accepted';
}

export type CommitRestoreResult = CommitRestoreAccepted | CommitRestoreConflict;

/** Thứ một lượt ghi phục hồi cần biết. `baseVersion` là `sequence` của bản đang hiện. */
export interface CommitRestoreInput {
  readonly floorId: string;
  readonly baseVersion: number;
  readonly restoredVersion: VersionEntry;
}

export interface CreateVersionHistoryGatewayOptions {
  /** Tầng mà lịch sử này thuộc về — `restoreVersion` đòi nó, xem `restore.ts:50`. */
  readonly floorId: string;
  /** Ai đang phục hồi. Đi thẳng vào `VersionMetadata.creatorId`; không có bộ tra nào khác. */
  readonly creatorId: string;
  /** Lịch sử bơm sẵn — dùng khi chưa có bộ nạp (xem mục 1 của bản kê nợ). */
  readonly entries?: readonly VersionHistoryEntry[];
  /** Bộ nạp thật, ngày endpoint liệt kê tồn tại. Phải tự đi qua `src/lib/http`. */
  readonly loadVersions?: (floorId: string) => Promise<readonly VersionHistoryEntry[]>;
  /** Lượt ghi phục hồi ra máy chủ. Không bơm ⇒ phục hồi chạy tại chỗ, không có 409. */
  readonly commitRestore?: (input: CommitRestoreInput) => Promise<CommitRestoreResult>;
  /** Danh sách thành viên để tra `changedBy` sang tên hiển thị. Không có ⇒ giữ chuỗi thô. */
  readonly members?: readonly VersionActor[];
  /** Đường gắn nhãn, nếu nơi ráp có. Không bơm ⇒ `canTagVersion` là `false`. */
  readonly tagVersion?: (versionId: string, label: string) => Promise<VersionMetadata>;
  /** Nơi ráp có sẵn đường xuất một phiên bản hay không. Mặc định `false` — NOT FOUND. */
  readonly canExportVersion?: boolean;
  /** Đồng hồ. Bơm được để test không phụ thuộc giờ máy. */
  readonly now?: () => Date;
}

/* -------------------------------------------------------------------------- */
/* 4 — Phép chuyển thuần                                                      */
/* -------------------------------------------------------------------------- */

/** Ảnh chụp đầy đủ của một mục lịch sử, hoặc `null` khi mục đó chỉ còn siêu dữ liệu. */
export function readFullVersion(
  history: readonly VersionHistoryEntry[],
  versionId: string,
): VersionEntry | null {
  for (const entry of history) {
    if (entry.version.id === versionId) {
      return entry.kind === 'full' ? entry.version : null;
    }
  }

  return null;
}

/**
 * Những thay đổi mà lượt phục hồi mang theo, dưới dạng `FieldChange` — đầu vào
 * `resolveConflict` đòi.
 *
 * Lấy từ chính `diffVersions`, không tự dò: chỉ các mục `kind: 'changed'` mang `field`
 * (xem `diff.ts:87-93`), và đúng bốn trường ấy khớp `FieldChange` không cần ép kiểu.
 */
export function toFieldChanges(diff: VersionDiff): FieldChange[] {
  const changes: FieldChange[] = [];

  for (const entry of diff.changed as readonly DiffEntry[]) {
    if (entry.field === undefined) {
      continue;
    }

    changes.push({
      entityId: entry.entityId,
      entityType: entry.entityType,
      field: entry.field,
      value: entry.newValue,
    });
  }

  return changes;
}

/** Số chữ cái một `Avatar` không ảnh hiện được. */
const INITIALS_LENGTH = 2;

/**
 * Chữ cái đầu của một cái tên, cho ô đại diện không ảnh.
 *
 * Chép logic của `ShareDialog/shareDialogGateway.ts:150` thay vì nhập nó về: file kia kéo
 * theo `@/api/appClient` và `@/store`, và một `import` từ đây sẽ lôi cả hai vào phần gói
 * của tuyến lịch sử phiên bản — cổng kích thước gói đo theo TỪNG tuyến. Bảy dòng thuần
 * rẻ hơn một phụ thuộc chéo màn.
 *
 * Không có chữ nào đọc được thì trả chuỗi rỗng, và view vẽ ô trống thay vì một dấu hỏi
 * giả vờ là tên.
 */
export function initialsOf(name: string): string {
  const words = name.trim().split(/\s+/u).filter((word) => word.length > 0);
  if (words.length === 0) {
    return '';
  }

  const first = words[0] ?? '';
  const last = words[words.length - 1] ?? '';
  const letters = words.length === 1 ? first.slice(0, 1) : `${first.slice(0, 1)}${last.slice(0, 1)}`;

  return letters.slice(0, INITIALS_LENGTH).toLocaleUpperCase('vi-VN');
}

/** `changedBy` sang tên hiển thị; lùi về chính chuỗi thô khi không tra được. */
export function readActorName(
  changedBy: string,
  members: readonly VersionActor[] | undefined,
): string {
  return members?.find((member) => member.id === changedBy)?.name ?? changedBy;
}

/**
 * Thân 409 thành câu người đọc hiểu.
 *
 * `message` nêu AI đã sửa; `detail` là `ConflictResolution.description` do
 * `resolveConflict` sinh (`conflict.ts:76,88`) — màn không tự đếm và không tự kể lại nội
 * dung thay đổi từ xa. Không có trường nào cho phép ghi đè, và đó là chủ ý.
 */
export function toConflictNotice(
  remoteChanges: readonly RemoteFieldChange[],
  description: string,
  members: readonly VersionActor[] | undefined,
): ConflictNoticeModel {
  const first = remoteChanges[0];
  const actorName = first === undefined ? 'người khác' : readActorName(first.changedBy, members);
  const changedOn = first === undefined ? null : formatCalendarDate(new Date(first.changedAt));

  return {
    actorName,
    message:
      changedOn === null
        ? `${actorName} đã sửa bản vẽ này từ lúc bạn mở trang, nên lượt phục hồi chưa được ghi.`
        : `${actorName} đã sửa bản vẽ này ngày ${changedOn}, sau lúc bạn mở trang, nên lượt phục hồi chưa được ghi.`,
    detail: description.length === 0 ? null : description,
    dismissLabel: 'đã hiểu',
  };
}

/**
 * Siêu dữ liệu của phiên bản MỚI mà lượt phục hồi sinh ra — mục 3 của bản kê nợ.
 *
 * `sequence` là số lớn nhất đang có cộng một, đúng thứ test `diff.test.ts:286-313` chờ
 * đợi (đang ở v15, phục hồi v14, sinh ra v16). Đếm phiên bản vì thế **tăng thêm một**,
 * không bao giờ giảm.
 */
export function buildRestoredVersionMetadata(input: {
  readonly history: readonly VersionHistoryEntry[];
  readonly source: VersionEntry;
  readonly creatorId: string;
  readonly now: () => Date;
}): VersionMetadata {
  let highest = input.source.sequence;
  for (const entry of input.history) {
    if (entry.version.sequence > highest) {
      highest = entry.version.sequence;
    }
  }

  return {
    createdAt: input.now().toISOString(),
    creatorId: input.creatorId,
    id: createUuid(),
    note: `phục hồi nội dung của phiên bản v${input.source.sequence}`,
    sequence: highest + 1,
  };
}

/* -------------------------------------------------------------------------- */
/* 5 — Cổng                                                                   */
/* -------------------------------------------------------------------------- */

/**
 * Cổng thật.
 *
 * Giữ lịch sử đã nạp trong một biến đóng vì hợp đồng cho `restore(versionId)` đúng MỘT
 * tham số, mà phép phục hồi cần cả ảnh chụp nguồn lẫn bản đang hiện — cả hai chỉ có trong
 * danh sách. Biến ấy được đặt lại ở mỗi lượt {@link VersionHistoryGateway.listVersions},
 * nên nó là bộ nhớ tạm của lượt đọc gần nhất chứ không phải một kho song song.
 */
export function createVersionHistoryGateway(
  options: CreateVersionHistoryGatewayOptions,
): VersionHistoryGateway {
  const readNow = (): Date => options.now?.() ?? new Date();

  let history: readonly VersionHistoryEntry[] = options.entries ?? [];

  const capabilities: VersionHistoryCapabilities = {
    canShowCurrentModel3d: true,
    canHighlightEntity: true,
    canTagVersion: options.tagVersion !== undefined,
    canGroupByAuthor: false,
    canExportVersion: options.canExportVersion ?? false,
  };

  const listVersions = async (floorId: string): Promise<readonly VersionHistoryEntry[]> => {
    if (options.loadVersions !== undefined) {
      history = await options.loadVersions(floorId);
      return history;
    }

    if (options.entries === undefined) {
      throw new Error(NO_VERSION_SOURCE_REASON);
    }

    return history;
  };

  const diff = async (leftVersionId: string, rightVersionId: string): Promise<VersionDiff> => {
    const left = readFullVersion(history, leftVersionId);
    const right = readFullVersion(history, rightVersionId);
    if (left === null || right === null) {
      throw new Error(SNAPSHOT_MISSING_REASON);
    }

    return diffVersions(left.snapshot, right.snapshot);
  };

  const restore = async (versionId: string): Promise<RestoreOutcome> => {
    const source = readFullVersion(history, versionId);
    const currentEntry = history[0];
    if (source === null || currentEntry === undefined || currentEntry.kind !== 'full') {
      throw new Error(SNAPSHOT_MISSING_REASON);
    }

    const current = currentEntry.version;
    const { restoredVersion } = restoreVersion({
      floorId: options.floorId,
      newVersion: buildRestoredVersionMetadata({
        history,
        source,
        creatorId: options.creatorId,
        now: readNow,
      }),
      sourceVersion: source,
    });

    if (options.commitRestore !== undefined) {
      const outcome = await options.commitRestore({
        floorId: options.floorId,
        baseVersion: current.sequence,
        restoredVersion,
      });

      if (outcome.kind === 'conflict') {
        const resolution = resolveConflict({
          baseVersion: current.sequence,
          localChanges: toFieldChanges(diffVersions(current.snapshot, restoredVersion.snapshot)),
          remoteChanges: outcome.body.remoteChanges,
          serverVersion: outcome.body.currentVersion,
        });

        return {
          kind: 'conflict',
          conflict: toConflictNotice(
            outcome.body.remoteChanges,
            resolution.description,
            options.members,
          ),
        };
      }
    }

    const previous = history;
    history = appendVersionToHistory(history, restoredVersion);

    const undoTicket: UndoTicket = createUndoTicket({
      description: `phục hồi nội dung của phiên bản v${source.sequence}`,
      undo: () => {
        history = previous;
      },
    });

    return { kind: 'restored', restoredVersion, history, undoTicket };
  };

  const undoRestore = async (ticket: UndoTicket): Promise<readonly VersionHistoryEntry[]> => {
    ticket.undo();
    return history;
  };

  return {
    capabilities,
    listVersions,
    diff,
    restore,
    undoRestore,
    ...(options.tagVersion !== undefined ? { tagVersion: options.tagVersion } : {}),
  };
}
